#CREATE DATABASE SPRING_MVC_TRAINING_VER2;
USE SPRING_MVC_TRAINING_VER2;

CREATE TABLE POST (
	POST_ID   BIGINT 		 AUTO_INCREMENT PRIMARY KEY,
    USER_ID   VARCHAR(50)	 NOT NULL,
    SUBJECT    VARCHAR(100)  NOT NULL,
    CONTENT    VARCHAR(2000) NOT NULL,
    READ_CNT   BIGINT 	     DEFAULT 0,
    ENROLL_AT  TIMESTAMP 	 DEFAULT NOW()
);

CREATE TABLE REPLY (
	REPLY_ID   BIGINT 		 AUTO_INCREMENT PRIMARY KEY,
	USER_ID    VARCHAR(50)	 NOT NULL,
	POST_ID   BIGINT 		 NOT NULL,
    CONTENT    VARCHAR(2000) NOT NULL,
	ENROLL_AT  TIMESTAMP 	 DEFAULT NOW(),
	FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID)
	ON DELETE CASCADE
);

CREATE TABLE USER (
	USER_ID 			  VARCHAR(50)  PRIMARY KEY ,
	NICKNAME 			  VARCHAR(100) NOT NULL UNIQUE,
	PASSWD 				  VARCHAR(255) NOT NULL,
	PROFILE_ORIGINAL_NAME VARCHAR(255) NOT NULL,
	PROFILE_UUID 		  VARCHAR(255) NOT NULL,
	EMAIL 				  VARCHAR(255) NOT NULL,
	ROLE 				  VARCHAR(50)  DEFAULT 'user',
	JOIN_AT 			  TIMESTAMP    DEFAULT NOW()
);


CREATE TABLE ADMIN (
	ADMIN_ID 	 VARCHAR(255) PRIMARY KEY,
	ADMIN_PASSWD VARCHAR(255) NOT NULL,
	ROLE 		 VARCHAR(255) DEFAULT 'admin',
	JOIN_AT      TIMESTAMP    DEFAULT NOW()
);

INSERT INTO ADMIN(ADMIN_ID , ADMIN_PASSWD) VALUES ('jarvis' , 'Heyjarvis!');


