CREATE DATEBASE SPRING_JPA_TRAINING_VER1;
USE SPRING_JPA_TRAINING_VER1;

CREATE TABLE BOARD (
	BOARD_ID 	BIGINT 			PRIMARY KEY AUTO_INCREMENT,
    PASSWD 		VARCHAR(200)	NOT NULL,
    WRITER 		VARCHAR(50)		NOT NULL,
    SUBJECT 	VARCHAR(50)		NOT NULL,
   	CONTENT 	VARCHAR(2000)	NOT NULL,
    READ_CNT  	BIGINT			NOT NULL,
    ENROLL_AT 	TIMESTAMP		NOT NULL
);