#CREATE DATABASE SPRING_JPA_EX;
USE SPRING_JPA_EX;

# 테이블 생성
CREATE TABLE APPLICANT(
	APPLICANT_ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME   		  VARCHAR(255)
);

CREATE TABLE PROFILE(
	PROFILE_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
	APPLICANT_ID  BIGINT,
	PROFILE       VARCHAR(255)
);


# 테스트 데이터
INSERT INTO 
		APPLICANT(NAME)
VALUES 
		('지원자1'),
		('지원자2'),
		('지원자3');
		
INSERT INTO 
		PROFILE(APPLICANT_ID , PROFILE)
VALUES 
		(1, '지원자1 프로필입니다.'),
		(2, '지원자2 프로필입니다.'),
		(3, '지원자3 프로필입니다.');

